---
on:
  push:
    tags:
      - "*"

# Help here: https://github.com/espressif/esp-idf-ci-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v6.0
        target: esp32s3
        path: '.'
    - name: Pack binaries
      run: >
        cp bin-README build/README;
        cd build;
        zip tinyecg-${{ github.ref_name }}.zip
        flash_args
        bootloader/bootloader.bin
        tinyecg.bin
        partition_table/partition-table.bin
      shell: bash
    - name: Upload build
      run: >
        gh release create ${{ github.ref_name }}
        build/tinyecg-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash
