---
on:
  push:
    tags:
      - "*"

# Help here: https://github.com/espressif/esp-idf-ci-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v6.0
        target: esp32s3
        path: '.'
    - name: Pack binaries
      run: >
        mkdir dist dist/bootloader dist/partition_table;
        cp bin-README dist/README;
        cp build/bootloader/bootloader.bin dist/bootloader/;
        cp build/partition_table/partition-table.bin dist/partition_table/;
        cp build/tinyecg.bin build/flash_args dist/;
        cd dist;
        zip tinyecg-${{ github.ref_name }}.zip
        README
        flash_args
        bootloader/bootloader.bin
        tinyecg.bin
        partition_table/partition-table.bin
      shell: bash
    - name: Upload build
      run: >
        gh release create ${{ github.ref_name }}
        dist/tinyecg-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash
